apiVersion: v1
kind: Service
metadata:
  name: {{ include "helloWeb3.fullname" . }}
  labels:
    {{- include "helloWeb3.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
    - port: {{ .Values.metrics.port }}
      targetPort: 8080
      protocol: TCP
      name: metrics
  selector:
    {{- include "helloWeb3.selectorLabels" . | nindent 4 }}
