# General settings
nameOverride: ""
fullnameOverride: ""

gcp:
  project_id: ""

# Image settings
image:
  repository: "gcr.io/{{ .Values.gcp.project_id }}/{{ .Values.image.name }}"
  name: "bcw-research-app"
  pullPolicy: IfNotPresent
  tag: "latest"

# Replica settings
replicaCount: 3

# Service settings
service:
  type: LoadBalancer
  port: 3000

# Ingress settings
ingress:
  enabled: true
  className: "gce"
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Autoscaling settings
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Resource requests and limits
resources:
  limits:
    cpu: "500m"
    memory: "1Gi"
  requests:
    cpu: "200m"
    memory: "512Mi"

# Pod and container security contexts
podSecurityContext: {}
securityContext: {}

# Pod annotations (for metrics scraping, etc.)
podAnnotations: {}

# Node selector, affinity, and tolerations
nodeSelector: {}
affinity: {}
tolerations: []

# Service account settings
serviceAccount:
  create: true
  name: ""
  annotations: {}

# Image pull secrets
imagePullSecrets: []

# Metrics configuration
metrics:
  enabled: true
  port: 3000

