name: Deploy to GKE with Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Google Cloud SDK
      run: |
        echo "Installing Google Cloud SDK..."
        sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
        sudo apt-get update && sudo apt-get install -y google-cloud-sdk

    - name: Authenticate to Google Cloud
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      run: |
        echo "${GCP_SA_KEY}" > /tmp/gcp_key.json
        gcloud auth activate-service-account --key-file=/tmp/gcp_key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Install gke-gcloud-auth-plugin
      run: |
        sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

    - name: Set up Kubernetes credentials
      env:
        GKE_CLUSTER_LOCATION: ${{ secrets.GKE_CLUSTER_LOCATION }}
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --location $GKE_CLUSTER_LOCATION
        kubectl config current-context  # Verifies if context is set correctly

    - name: Verify Connection to GKE
      run: |
        kubectl get nodes  # This confirms if the cluster is reachable

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Deploy to GKE with Helm
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      run: |
        helm upgrade --install hello-web3 ./helm/helloWeb3 \
          --namespace default \
          --set image.repository=gcr.io/$GCP_PROJECT_ID/bcw-research-app \
          --set image.tag=latest \
          --set service.port=8080 \
          --set service.type=LoadBalancer \
          --set metrics.enabled=true \
          --set metrics.port=3000

    - name: Wait for External IP
      run: |
        # Wait for external IP to be assigned
        for i in {1..10}; do
          EXTERNAL_IP=$(kubectl get svc hello-web3-helloweb3 -n default -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          if [ -n "$EXTERNAL_IP" ]; then
            echo "External IP assigned: $EXTERNAL_IP"
            echo "EXTERNAL_IP=$EXTERNAL_IP" >> $GITHUB_ENV
            break
          fi
          echo "Waiting for external IP..."
          sleep 15
        done

    - name: Deploy Prometheus
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update
        helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
          --namespace monitoring --create-namespace \
          --set additionalScrapeConfigs[0].job_name=helloweb3_app \
          --set additionalScrapeConfigs[0].scrape_interval=60s \
          --set additionalScrapeConfigs[0].static_configs[0].targets[0]="${{ env.EXTERNAL_IP }}:3000"

    - name: Deploy Grafana
      run: |
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo update
        helm upgrade --install grafana grafana/grafana \
          --namespace grafana --create-namespace \
          --set service.type=LoadBalancer \
          --set service.port=80

    - name: Apply ServiceMonitor for app.js App
      run: kubectl apply -f kubernetes/servicemonitor.yaml
    
    - name: Clean up
      run: rm /tmp/gcp_key.json
